[package]

name = "robigo-luculenta"
version = "0.1.1"
authors = [ "dev@veniogames.com" ]

[dependencies.image]
version = "0.2.1"
git = "https://github.com/PistonDevelopers/image.git"

[dependencies]
rand = "0.1.4"
time = "0.1.20"
