[package]

name = "robigo-luculenta"
version = "0.1.1"
authors = [ "dev@veniogames.com" ]

[dependencies.image]
version = "0.2.0"
git = "https://github.com/PistonDevelopers/image.git"

[dependencies]
rand = "0.1.2"
time = "0.1.17"
