[package]

name = "robigo-luculenta"
version = "0.1.1"
authors = [ "dev@veniogames.com" ]

[dependencies.image]
version = "0.1.0"
git = "https://github.com/PistonDevelopers/image.git"

[dependencies.time]
version = "0.0.1"
git = "https://github.com/rust-lang/time.git"
