[package]

name = "robigo-luculenta"
version = "0.1.1"
authors = [ "dev@veniogames.com" ]

[dependencies.image]
version = "0.3.4"
git = "https://github.com/PistonDevelopers/image.git"
default-features = false
features = ["png"]

[dependencies]
num_cpus = "0.1.0"
rand = "0.3.7"
time = "0.1.24"
