[package]

name = "robigo-luculenta"
version = "0.1.1"
authors = [ "dev@veniogames.com" ]

[dependencies.image]
version = "0.3.0"
git = "https://github.com/PistonDevelopers/image.git"
default-features = false
features = ["png"]

[dependencies]
rand = "0.3.0"
time = "0.1.21"
